name: PHP lint

on:
  push:
    branches:
      - master
      - 2.x
    paths:
      - '**.php'
      - '**composer.json'
  pull_request:
    branches:
      - master
      - 2.x
    paths:
      - '**.php'
      - '**composer.json'
    types:
      - opened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-lint:
    name: PHP lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/setup
        with:
          PHP_TOOLS: 'parallel-lint,cs2pr'
          INSTALL_DEPS: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
           files: '**.php'

      - name: Run PHP lint
        if: steps.changed-files.outputs.all_changed_files != ''
        run: parallel-lint --exclude .git --exclude vendor --checkstyle ${{ join(steps.changed-files.outputs.all_changed_files, ' ') }} | cs2pr
